default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: 5
  username: <%= ENV['QUEUE_DATABASE_USERNAME'] || "postgres" %>
  password: <%= ENV['QUEUE_DATABASE_PASSWORD'] || "postgres" %>

development:
  <<: *default
  database: queue_jobs_development

test:
  <<: *default
  database: queue_jobs_test

staging:
  <<: *default
  database: queue_jobs_staging

production:
  <<: *default
  database: queue_jobs_production
